<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Visitor extends Model
{
    use HasFactory;
      protected $table = 'visitors';
    protected $primaryKey = 'id_visitor';

       public function Vendor_Visitor()
    {
        return $this->hasMany(Vendor_Visitor::class, 'id_visitor');
    }

       protected $fillable = [
        'email',
        'request_date_from',
        'request_date_to',
        'purpose_visit',
        'purpose_detail',
        'building',
        'level',
        'specific_location',
        'pic_name',
        'pic_contact',
        'car_plate_no',
        'vehicle_type',
        'name_1',
        'id_card_1',
        'name_2',
        'id_card_2',
        'name_3',
        'id_card_3',
        'name_4',
        'id_card_4',
        'name_5',
        'id_card_5',
        'name_6',
        'id_card_6',
        'name_7',
        'id_card_7',
        'name_8',
        'id_card_8',
        'name_9',
        'id_card_9',
        'name_10',
        'id_card_10',
        'name_11',
        'id_card_11',
        'name_12',
        'id_card_12',
        'name_13',
        'id_card_13',
        'name_14',
        'id_card_14',
        'name_15',
        'id_card_15',
        'name_16',
        'id_card_16',
        'name_17',
        'id_card_17',
        'name_18',
        'id_card_18',
        'name_19',
        'id_card_19',
        'name_20',
        'id_card_20',
        'name_21',
        'id_card_21',
        'name_22',
        'id_card_22',
        'name_23',
        'id_card_23',
        'name_24',
        'id_card_24',
        'name_25',
        'id_card_25',
        'name_26',
        'id_card_26',
        'name_27',
        'id_card_27',
        'name_28',
        'id_card_28',
        'name_29',
        'id_card_29',
        'name_30',
        'id_card_30',
        'material_1',
        'quantity_1',
        'material_2',
        'quantity_2',
        'material_3',
        'quantity_3',
        'material_4',
        'quantity_4',
        'material_5',
        'quantity_5',
        'material_6',
        'quantity_6',
        'material_7',
        'quantity_7',
        'material_8',
        'quantity_8',
        'material_9',
        'quantity_9',
        'material_10',
        'quantity_10',
        'material_11',
        'quantity_11',
        'material_12',
        'quantity_12',
        'material_13',
        'quantity_13',
        'material_14',
        'quantity_14',
        'material_15',
        'quantity_15',
        'material_16',
        'quantity_16',
        'material_17',
        'quantity_17',
        'material_18',
        'quantity_18',
        'material_19',
        'quantity_19',
        'material_20',
        'quantity_20',
        'material_21',
        'quantity_21',
        'material_22',
        'quantity_22',
        'material_23',
        'quantity_23',
        'material_24',
        'quantity_24',
        'material_25',
        'quantity_25',
        'material_26',
        'quantity_26',
        'material_27',
        'quantity_27',
        'material_28',
        'quantity_28',
        'material_29',
        'quantity_29',
        'material_30',
        'quantity_30',
        'upload_id_card_foto',
        'primary_number',
        'company_name',
        'permit_number',
        'status',

    ];
}
